---
ID: "b2bb510f-a3c8-47c3-ba7c-1bfe56a79f05"
Parent: "d145a02d-3f6e-4966-b0e5-4ef1f1beda26"
Template: "d145a02d-3f6e-4966-b0e5-4ef1f1beda26"
Path: /sitecore/templates/Project/WestfieldInsurance/Page Content/Full Width Widget/Full Width Widget Folder/__Standard Values
SharedFields:
  - ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
    Hint: __Masters
    Value: "{1BE999A8-5A98-4631-8FF2-2FA91D847E9B}"
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
            Hint: __Created
            Value: 20231016T190059Z
          - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
            Hint: __Owner
            Value: |
              sitecore\tim.shanahan@americaneagle.com
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\tim.shanahan@americaneagle.com
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "3c621155-aa5d-435d-9cb3-eb7c872465da"
          - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
            Hint: __Updated by
            Value: |
              sitecore\tim.shanahan@americaneagle.com
          - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
            Hint: __Updated
            Value: 20231016T190112Z
