---
ID: "304ea3ad-e59b-4624-963c-f36d2c68b752"
Parent: "7a949d1e-bac2-4514-90b5-7f5dcd22dfea"
Template: "6b8aabef-d650-46e0-97d0-c0b04f7f016b"
Path: /sitecore/content/WestfieldInsurance/Sites/WestfieldInsurance/Presentation/Styles/Comparison Matrix Themes/Default
SharedFields:
- ID: "09147fb2-ebfb-4949-8c8e-26a424409d5e"
  Hint: Value
  Value: "default-comparison-matrix"
- ID: "69bb49f3-da64-4b0e-abd6-184b832ff6ab"
  Hint: Allowed Renderings
  Value: "{771D6D33-8DFF-43F1-9B17-5BA1C02F7637}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231101T151222Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\prerak.pandey@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\prerak.pandey@americaneagle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "3d5dceb6-51da-4dfd-b7b1-c0b55a867820"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\prerak.pandey@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240131T145814Z
