---
ID: "4e937ddc-1ccb-431e-93bc-1d5134debf1a"
Parent: "dd3b7313-9d96-42a4-a77a-d722a5cbb0ee"
Template: "4ad81f4d-e79c-475d-a270-9194d96d46b5"
Path: /sitecore/content/WestfieldInsurance/Sites/WestfieldInsurance/Home/Tim Test/Training Page
SharedFields:
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{B1984AA8-813E-40C8-80B8-9C64A5A8A203}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "1db9908b-4509-4846-8461-e155ef730fc2"
      Hint: Title
      Value: Training Page
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240117T174411Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "8a3e6082-7126-4f92-9051-a0480ddd9076"
      Hint: BreadcrumbTitle
      Value: Training Page
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "aa4c5eb2-08fa-4ca5-be6c-91f419729d92"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240214T194537Z
