---
ID: "48f8871a-c239-4761-9d0a-047d4ecf9bce"
Parent: "051d332a-c88c-4236-bfe2-5b3442ac9131"
Template: "051d332a-c88c-4236-bfe2-5b3442ac9131"
Path: /sitecore/templates/Project/WestfieldInsurance/Page Content/Header/Header/__Standard Values
SharedFields:
  - ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
    Hint: __Masters
    Value: |
      {6DA114C1-FB9D-41B2-92B3-AFEB3234F871}
      {66BCE5F9-6236-4055-983B-5E9FD3532E7F}
      {82B01987-5609-4E99-B97C-BA243850E42E}
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
            Hint: __Created
            Value: 20230929T162235Z
          - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
            Hint: __Owner
            Value: |
              sitecore\tim.shanahan@americaneagle.com
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\tim.shanahan@americaneagle.com
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "097da8bf-8fd4-4797-bc9e-267fe767b5a8"
          - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
            Hint: __Updated by
            Value: |
              sitecore\tim.shanahan@americaneagle.com
          - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
            Hint: __Updated
            Value: 20231014T112907Z
