---
ID: "812ca0dc-8909-4bc0-937b-aaecf1e385c1"
Parent: "f87a85fe-38e9-47ea-84fd-114b62d4dfdd"
Template: "1105b8f8-1e00-426b-bf1f-c840742d827b"
Path: /sitecore/content/WestfieldInsurance/Sites/WestfieldInsurance/Presentation/Page Designs/Default
SharedFields:
- ID: "0966b999-0d0e-4278-acc9-9da69d461fe6"
  Hint: PartialDesigns
  Value: "{F8436E7C-9469-4358-BC17-25A90A3EE321}|{B077C438-F443-44F0-A8C9-C308CA72FE9F}"
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{DEB80EB3-0EE6-44FE-ACE2-2FF000BCE5D1}" />
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231010T201216Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\jason.dilday@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\jason.dilday@americaneagle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "543efb13-f5f1-4e78-8178-24023c0f3129"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240221T200021Z
