---
ID: "caed7204-7ea2-4d19-a82c-b41172352692"
Parent: "ef9b9ef2-97a3-4361-bc91-10c8917c6e8e"
Template: "ef9b9ef2-97a3-4361-bc91-10c8917c6e8e"
Path: /sitecore/templates/Project/WestfieldInsurance/Page Content/Find Agent/Find An Agent Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {00E84CB8-0D60-45E0-9B27-95D295B9B4CE}
    {0E347486-A7F6-4CBC-9E4A-C420F3FD43CC}
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231206T184722Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ce3cf63f-f045-46fe-bdb9-db349d0ae9c7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231206T184831Z
