---
ID: "b9856c3e-c831-4987-b8e3-8a57b194cbe2"
Parent: "37975c04-337d-484b-9db6-eee6b9091f08"
Template: "37975c04-337d-484b-9db6-eee6b9091f08"
Path: /sitecore/templates/Project/WestfieldInsurance/Page Content/Interior Hero Banner/Interior Hero Banner/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230925T185150Z
    - ID: "3142f826-3a3a-4d1c-afa4-84e7d71385d4"
      Hint: Title
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7428f17c-ac09-48ca-9338-bc6b3a78a32d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\prerak.pandey@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231101T153841Z
