---
ID: "1ff2ba23-70c6-49d7-8438-a43b173cd7e4"
Parent: "3ba41eef-3400-4a6b-bf0e-4fb9ef1a9356"
Template: "3ba41eef-3400-4a6b-bf0e-4fb9ef1a9356"
Path: /sitecore/templates/Project/WestfieldInsurance/Page Content/Accordion/Custom Accordion Item/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230925T185150Z
    - ID: "3142f826-3a3a-4d1c-afa4-84e7d71385d4"
      Hint: Title
      Value: 
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "b8d071cb-e007-4a76-9232-b7077f171c75"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\prerak.pandey@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231107T181541Z
