---
ID: "75178530-b6d1-46b3-b47c-9ba8d1ef219c"
Parent: "9055a29b-920a-4711-a016-dc8990dc2dcc"
Template: "9055a29b-920a-4711-a016-dc8990dc2dcc"
Path: /sitecore/templates/Project/WestfieldInsurance/Page Content/Career Listing/Career Listings Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{9A0F3EE6-769E-4BE8-99AD-5AA40694FD8F}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230928T214447Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "0dcf2ce8-e570-459f-afbe-07626ef79cb7"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240221T200745Z
