---
ID: "a7a4cf03-b15d-4053-addf-46d45925eb86"
Parent: "0e347486-a7f6-4cbc-9e4a-c420f3fd43cc"
Template: "0e347486-a7f6-4cbc-9e4a-c420f3fd43cc"
Path: /sitecore/templates/Project/WestfieldInsurance/Page Content/Find Agent/Insurance Type Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{DA9D9F3A-1ABF-4B91-8344-0E768C0531D7}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231206T182538Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "914c0bb0-8540-4127-b3bf-8f71e2870751"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231206T182605Z
