---
ID: "367df32a-c227-4d44-bb99-d12c9e959e74"
Parent: "05c23ef0-5ba9-4591-a130-7e6900bc5859"
Template: "fe5dd826-48c6-436d-b87a-7c4210c7413b"
Path: /sitecore/media library/Project/WestfieldInsurance/WestfieldInsurance/Local/ProductComparisons
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20240104T143224Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\prerak.pandey@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\prerak.pandey@americaneagle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "a98eeb59-c1ea-45e2-897d-54807dcac002"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\prerak.pandey@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240104T143224Z
