---
ID: "17666e32-d4a7-4709-a543-c4cb841852c4"
Parent: "cb63f335-6f58-44c7-b3d8-400b06ae74d4"
Template: "cb63f335-6f58-44c7-b3d8-400b06ae74d4"
Path: /sitecore/templates/Project/_Base/_ComponentBase/_Title/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230925T173541Z
    - ID: "3142f826-3a3a-4d1c-afa4-84e7d71385d4"
      Hint: Title
      Value: $name
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "55be957f-67c3-432e-807e-e2a4e3a2522f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230925T173600Z
