---
ID: "ed4aa970-d6b7-4294-9ee7-38a0a4b27e8c"
Parent: "26154a93-8630-47b5-a249-f22911b1fd5e"
Template: "26154a93-8630-47b5-a249-f22911b1fd5e"
Path: /sitecore/templates/Project/WestfieldInsurance/Page Content/Products Cards/Products Cards Container Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: "{40BF9474-C9E4-4AFC-9016-F83A726BE42B}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230928T214447Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5ea57624-60da-471d-80ba-8fb9b1f7e761"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20240221T200619Z
