---
ID: "230fbea2-b553-4de8-9d42-dc9a67ecfdf3"
Parent: "889d0741-af5b-47c5-af13-ba22ddc8920d"
Template: "889d0741-af5b-47c5-af13-ba22ddc8920d"
Path: /sitecore/templates/Project/WestfieldInsurance/Headless Site/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20230920T151245Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "ae162ac4-844a-4b8c-be76-b28241e97b0a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230920T151245Z
