---
ID: "736fffde-5ebd-4cf0-ae8c-f4496405034a"
Parent: "82b01987-5609-4e99-b97c-ba243850e42e"
Template: "82b01987-5609-4e99-b97c-ba243850e42e"
Path: /sitecore/templates/Project/WestfieldInsurance/Page Content/Header/Featured Header Cards Folder/__Standard Values
SharedFields:
  - ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
    Hint: __Masters
    Value: "{E6114D50-0996-45A5-AA18-B7831C67986A}"
Languages:
  - Language: en
    Versions:
      - Version: 1
        Fields:
          - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
            Hint: __Created
            Value: 20231014T111845Z
          - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
            Hint: __Owner
            Value: |
              sitecore\tim.shanahan@americaneagle.com
          - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
            Hint: __Created by
            Value: |
              sitecore\tim.shanahan@americaneagle.com
          - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
            Hint: __Revision
            Value: "9ca54def-8d97-4679-984f-6fe7c433e90e"
          - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
            Hint: __Updated by
            Value: |
              sitecore\tim.shanahan@americaneagle.com
          - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
            Hint: __Updated
            Value: 20231014T111908Z
