---
ID: "dbbc612b-1fb0-4252-9989-59538d24eaed"
Parent: "0399b38d-9720-4f28-8588-291bf640ba07"
Template: "0399b38d-9720-4f28-8588-291bf640ba07"
Path: /sitecore/templates/Project/_Base/_PageBase/_BreadcrumbTitle/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20231114T022736Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "8a3e6082-7126-4f92-9051-a0480ddd9076"
      Hint: BreadcrumbTitle
      Value: $name
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d62714ed-2d49-44a7-92eb-7c0d09cf21c2"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\tim.shanahan@americaneagle.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20231114T022739Z
